function img = draw_cand_zoom(stats,rank,img,color)
	bbtight = stats(rank,2:end); 
	smallest = min(size(img)); 
	bb = bbtight + round([-1,1,-1,1] * 5);
	bb = max(bb,1);   
	bb(2) = min(bb(2),size(img,1)); 
	bb(4) = min(bb(4),size(img,2));
	img = draw_box(img,bbtight,color); 	
	img = img(bb(1):bb(2),bb(3):bb(4),:);
