OBJECTS = VehicleDynamics2D.o $(VIS_DIR)/plugins/so/Lidar2DVisual.so $(VIS_DIR)/plugins/so/Lidar2D.so
TARGETS = MagicLidarScanPublisher.so MagicPlatformSim.so MagicLidarScan2VisLidarData.so MagicPose2VisPose3D.so

include $(MAGIC_DIR)/Makefile.mk
include $(VIS_DIR)/plugins/src/plugins.mk


